#!/usr/bin/env python3
# TODO: replace stderr with "import logging"
from sys import stderr
from os import environ
import feedparser
import telegram
from time import sleep

class RSS:
    @staticmethod
    def get_unread_feed(name: str, url: str):
        feed = feedparser.parse(url) 

        try:
            with open(f"last-read/{name}", "r") as last_read_file:
                last_read_id = last_read_file.read().strip()
        except FileNotFoundError:
            pass
        
        feed_unread = []
        if "last_read_id" in locals():
            for item in feed.entries:
                if item.id == last_read_id:
                    break
                feed_unread.append(item)
        else:
            feed_unread = feed.entries
        
        feed_unread.reverse()
        return feed_unread
    
    @staticmethod
    def save_last_unread(name: str, id: str):
        with open(f"last-read/{name}", "w") as last_read_file:
            last_read_file.write(id)
            pass

class Telegram:
    # return read/sent sent id
    @staticmethod
    def update(name: str, feed: list, topic: str = "", disable_web_page_preview: bool = True) -> str:
        token = environ["TOKEN"]
        chat_id = environ[f"CHAT_ID_{name.upper()}"]
        
        bot = telegram.Bot(token)
        counter = 0
        if topic:
            topic += "\n\n"
        for article in feed:
            # telegram doesn't allow sending more than 20 messages per minute to the same chat
            if counter >= 20:
                counter = 0
                sleep(60)

            bot.send_message(chat_id, f"{topic}<a href=\"{article.link}\">{article.title}</a>\n{article.description}", parse_mode="HTML", disable_web_page_preview=disable_web_page_preview)
            counter += 1
            sleep(1)

        return feed[-1].id

if __name__ == "__main__":
    feed = RSS.get_unread_feed("phoronix", "https://www.phoronix.com/rss.php")
    if feed:
        last_read = Telegram.update("phoronix", feed)
        RSS.save_last_unread("phoronix", last_read)

    feed = RSS.get_unread_feed("cs", "https://blog.counter-strike.net/index.php/feed/")
    if feed:
        last_read = Telegram.update("cs", feed, "#CS_Blog")
        RSS.save_last_unread("cs", last_read)
